# Generated by Django 5.0.7 on 2024-07-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teacher_grade_level_remove_teacher_id_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='country',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='national_id_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='teacher',
            name='national_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='nationality',
            field=models.CharField(default='Kenya', max_length=40),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_hours',
            field=models.DurationField(default=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='years_of_experience',
            field=models.IntegerField(default=1),
        ),
    ]
