# Generated by Django 5.0.7 on 2024-07-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_teacher_country_remove_teacher_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teaching_hours',
            field=models.DurationField(default=60),
        ),
    ]
