# Generated by Django 5.0.7 on 2024-07-29 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_teaching_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teaching_hours',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
