# Generated by Django 5.0.7 on 2024-07-29 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_rename_names_of_teachers_class_class_electronic_items_and_more'),
        ('classroom_period', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomperiod',
            name='classroom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='class_name', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='classroomperiod',
            name='end_time',
            field=models.TimeField(auto_now=0, verbose_name=0),
        ),
        migrations.AlterField(
            model_name='classroomperiod',
            name='start_time',
            field=models.TimeField(auto_now=0, verbose_name=0),
        ),
    ]
