# Generated by Django 5.0.7 on 2024-07-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_class_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='names_of_teachers',
            new_name='class_electronic_items',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='number_of_classrooms',
            new_name='class_groups',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='academic_year',
            new_name='no_of_chairs',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='class',
            name='meeting_days',
        ),
        migrations.RemoveField(
            model_name='class',
            name='number_of_enrolled_students',
        ),
        migrations.AddField(
            model_name='class',
            name='class_lessons',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='class_motto',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='class_size',
            field=models.CharField(default='medium', max_length=40),
        ),
        migrations.AddField(
            model_name='class',
            name='class_student_representative',
            field=models.CharField(default='Ajema', max_length=40),
        ),
        migrations.AddField(
            model_name='class',
            name='no_of_tables',
            field=models.IntegerField(default=0),
        ),
    ]
