# Generated by Django 5.0.7 on 2024-07-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_courses_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='school_term',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='assement_requirements',
            new_name='teaching_materials',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='class_starting_time',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_discription',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_instructor',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_trainer_name',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='department',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='number_of_students',
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(default='course'),
        ),
        migrations.AddField(
            model_name='courses',
            name='number_of_assessments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='number_of_assignments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='requirements',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='courses',
            name='syllabus',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='courses',
            name='trainer',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
